################ This script is customized for use on PNNL's internal CI platform
################ This script runs docker commands that assume a container named 'hnx'
######### Autogenerate PR to merge release tag into master on Github
#### This will ensure that master on Github gets the latest release

echo "Creating PR to merge release tag into master"

# login to gh cli
docker exec hnx bash -c 'gh auth login --with-token < ghtoken.txt '
docker exec hnx bash -c 'gh auth status'

# checkout the HyperNetX repo
docker exec hnx bash -c 'gh repo clone https://github.com/pnnl/HyperNetX.git'
docker exec hnx bash -c 'git fetch --all'

# Check out the targeted temp branch we created earlier in CD process
docker exec hnx bash -c 'echo "Checking out the following tag...."'
docker exec hnx bash -c 'cat tempbranch.txt'
docker exec hnx bash -c 'cat tempbranch.txt | xargs git checkout'
docker exec hnx bash -c 'git branch -vv && git --no-pager show --name-only'

# Create the PR to merge release tag into master
docker exec hnx bash -c 'gh pr create --title "Autogenerated PR from latest release tag" --body "Merge newest release tag into master" --base master'
