################ This script is customized for use on PNNL's internal CI platform
################ This script runs docker commands that assume a container named 'hnx'
######### Autogenerate PR to update develop on Github
#### This will ensure that develop on Github is in sync with develop on Stash, the source of truth.

echo "Creating PR to merge latest commit on Stash develop into Github develop"

# login to gh cli
docker exec hnx bash -c 'gh auth login --with-token < ghtoken.txt '
docker exec hnx bash -c 'gh auth status'

# checkout the HyperNetX repo on Github
docker exec hnx bash -c 'gh repo clone https://github.com/pnnl/HyperNetX.git'

# Check out the targeted temp branch we created earlier in CD process
docker exec hnx bash -c 'git fetch --all'
docker exec hnx bash -c 'echo "Checking out the following branch...."'
docker exec hnx bash -c 'cat tempbranch.txt'
docker exec hnx bash -c 'cat tempbranch.txt | xargs git checkout'
docker exec hnx bash -c 'git branch -vv && git --no-pager show --name-only'

# Create the PR from the autogenerated develop-<shortened hash from latest commit> branch
docker exec hnx bash -c 'gh pr create --title "Autogenerated PR from latest push to develop" --body "Mirror develop from internal repo" --base develop'
